### PR TITLE
Add license

### LINKED ISSUE #18: Add Apache 2.0 license
Accordingly to our [previous discussion](https://github.com/lapoissonnerie/touiteur-api/issues/30), we will use the Apache 2.0 license.

### PR DESCRIPTION
**Pull request by AnastasiaPromtep**
Closes #18 
Depends on #19

### CODE REVIEW

**Comment by AnastasiaPromtep** [comment]
I know, I am lazy
I will rewrite the (git) history

**Comment by AnastasiaPromtep** [comment]
This branch has been checked out from the Add-login branch. Because the Add-login branch has not been merged yet, the git diff is showing more changes than it should be. I tried to merge locally the these branches one after the other and everything went fine. I will take care to always check out new branches from develop to avoid those confusing situations.

**Comment by maximelouet** [comment]
Okay, but I think you'll have to re-start from `develop` or update the `Add-login` branch here before it gets merged, otherwise we'll merge old changes to `develop`...

**Comment by maximelouet** [comment]
to rebase from develop or start over

**Comment by maximelouet** [comment]
GOOOOOOOOOOOOOOOOOOOOOOOOO

**Pull request merged**
